name: CI
on:
  pull_request:
  push:
    branches:
      - main
env:
  RAILS_ENV: test
jobs:
  test:
    name: "RSpec"
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/ci
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: ci
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: mkdir -p ./tmp/screenshots
      - run: bundle exec rake db:prepare
      - run: bundle exec rspec
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: capybara-screenshots
          path: ./tmp/screenshots/
          retention-days: 7
          if-no-files-found: ignore
  brakeman:
    name: "Security / brakeman"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec brakeman --exit-on-warn --no-progress --color --output /dev/stdout
